/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: El Alquimista𓁞 (https://sketchfab.com/ElCanciller)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/night-elf-druid-world-of-warcraft-fc1aa9a31ee3488583ccd9a2487862ec
title: Night Elf Druid - World of Warcraft
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/elf.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.nightelffemales_Body}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.Hair00_04_Dbl}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.Helm_Circlet_A_01Red}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.shoulder_leaher_pvpdruid_c_02red}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.polearm_2h_firelandsraid_d_01green}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.nightelffemales_Body}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.nightelffemales_Body}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.Cinto}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/elf.gltf");
