/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: VideoJames (https://sketchfab.com/fuzion)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/royal-apothecary-society-lab-annotated-aba28e9a3e6d4d7d9f78f636670c7e56
title: Royal Apothecary Society Lab - *Annotated!*
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/undercity.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-229.41, 163.17, 197.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.02}
          >
            <mesh
              geometry={nodes["Table_Material_#497_0"].geometry}
              material={materials.Material_497}
            />
          </group>
          <group
            position={[218.51, 164, 196.27]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.05, 1, 1]}
          >
            <mesh
              geometry={nodes["Table_Material_#498_0"].geometry}
              material={materials.Material_498}
            />
          </group>
          <group
            position={[1.55, 167.22, 197.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.18, 1.18, 1.12]}
          >
            <mesh
              geometry={nodes["Cauldron_Material_#495_0"].geometry}
              material={materials.Material_495}
            />
          </group>
          <group
            position={[241.07, 238.07, 250.33]}
            rotation={[3.11, -0.54, 3.09]}
            scale={[0.96, 0.96, 0.42]}
          >
            <mesh
              geometry={nodes["TomeO002_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-289.87, 203.65, 69.71]}
            rotation={[-Math.PI / 2, 0, 0.87]}
          >
            <mesh
              geometry={nodes["Barrel001_Material_#496_0"].geometry}
              material={materials.Material_496}
            />
          </group>
          <group
            position={[-254.43, 208.46, -16.36]}
            rotation={[-1.56, -0.06, 2.07]}
          >
            <mesh
              geometry={nodes["Barrel002_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group position={[-306.62, 205.56, 4.67]} rotation={[-1.47, 0, 2.36]}>
            <mesh
              geometry={nodes["Barrel003_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[-306.62, 279.78, -12.3]}
            rotation={[-1.78, -0.13, 2.09]}
          >
            <mesh
              geometry={nodes["Barrel004_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[233.22, 204.25, 80.86]}
            rotation={[-Math.PI / 2, 0, 1.22]}
          >
            <mesh
              geometry={nodes["Barrel005_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[317.45, 206.94, -24.72]}
            rotation={[-Math.PI / 2, 0, 2.92]}
          >
            <mesh
              geometry={nodes["Barrel006_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[224.8, 187.32, 314.8]}
            rotation={[-2.63, 0.52, -0.27]}
            scale={2.37}
          >
            <group position={[-0.04, 6.35, 2.47]}>
              <mesh
                geometry={nodes["Object069_Material_#1191_0"].geometry}
                material={materials.Material_1191}
              />
            </group>
          </group>
          <group
            position={[229.92, 187.02, 304.9]}
            rotation={[-1.49, -0.65, -0.65]}
            scale={1.79}
          >
            <group position={[0.25, -1.14, 1.12]}>
              <mesh
                geometry={nodes["Plane009_Material_#504_0"].geometry}
                material={materials.Material_504}
              />
            </group>
          </group>
          <group
            position={[236.05, 185.16, 305.85]}
            rotation={[-2.03, -0.08, -0.43]}
            scale={1.79}
          >
            <mesh
              geometry={nodes["Plane010_Material_#508_0"].geometry}
              material={materials.Material_508}
            />
            <mesh
              geometry={nodes["Plane010_Material_#507_0"].geometry}
              material={materials.Material_507}
            />
          </group>
          <group
            position={[229.32, 209.45, 326.24]}
            rotation={[-1.53, -0.01, 0.4]}
            scale={[4.26, 4.26, 2.84]}
          >
            <group position={[-9.81, 8.07, -39.21]}>
              <mesh
                geometry={nodes["Object076_18_-_Default_0"].geometry}
                material={materials["18_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[216.58, 224.23, 322.8]}
            rotation={[-1.53, -0.01, -1.95]}
            scale={1.26}
          >
            <mesh
              geometry={nodes["Cage002_Material_#439_0"].geometry}
              material={materials.Material_439}
            />
          </group>
          <group
            position={[-129.96, 270.67, -50.03]}
            rotation={[0, 0.06, 0]}
            scale={[0.96, 1, 1]}
          >
            <group position={[0, -14.07, -17.01]}>
              <mesh
                geometry={nodes["Box030_Material_#451_0"].geometry}
                material={materials.Material_451}
              />
            </group>
          </group>
          <group
            position={[122.21, 270.67, -55.22]}
            rotation={[0, -0.07, 0]}
            scale={[1, 1, 1.22]}
          >
            <group position={[0, -14.07, -17.01]}>
              <mesh
                geometry={nodes["Box031_Material_#452_0"].geometry}
                material={materials.Material_452}
              />
            </group>
          </group>
          <group
            position={[169.68, 271.85, -48.49]}
            rotation={[-0.59, -0.2, -0.23]}
            scale={2.36}
          >
            <group position={[0.25, -1.14, 1.12]}>
              <mesh
                geometry={nodes["Plane012_Material_#465_0"].geometry}
                material={materials.Material_465}
              />
            </group>
          </group>
          <group
            position={[-219.67, 183.96, 68.68]}
            rotation={[-2.16, -0.6, 0.71]}
            scale={1.21}
          >
            <group position={[-0.04, 6.35, 2.47]}>
              <mesh
                geometry={nodes["Object101_Material_#1191_0"].geometry}
                material={materials.Material_1191}
              />
            </group>
          </group>
          <group
            position={[-233.66, 184.55, 53.65]}
            rotation={[-1.54, -0.5, 1.17]}
            scale={1.79}
          >
            <mesh
              geometry={nodes["Plane013_Material_#508_0"].geometry}
              material={materials.Material_508}
            />
          </group>
          <group
            position={[-214.24, 209.53, 58.85]}
            rotation={[-1.61, 0, 1.96]}
            scale={[4.26, 4.26, 2.84]}
          >
            <group position={[-9.81, 8.07, -39.21]}>
              <mesh
                geometry={nodes["Object105_18_-_Default_0"].geometry}
                material={materials["18_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[-234.74, 186.68, 59.66]}
            rotation={[-0.98, 0.03, 0.89]}
            scale={1.79}
          >
            <group position={[0.25, -1.14, 1.12]}>
              <mesh
                geometry={nodes["Plane014_Material_#504_0"].geometry}
                material={materials.Material_504}
              />
            </group>
          </group>
          <group
            position={[-238.26, 184.9, 60.89]}
            rotation={[0.94, 0.2, -0.4]}
            scale={[-1.79, 1.79, 1.79]}
          >
            <mesh
              geometry={nodes["Plane015_Material_#507_0"].geometry}
              material={materials.Material_507}
            />
          </group>
          <group
            position={[221.67, 210.1, -54.79]}
            rotation={[-Math.PI / 2, 0, -2.71]}
            scale={[4.22, 4.22, 2.82]}
          >
            <group position={[-9.81, 8.07, -39.21]}>
              <mesh
                geometry={nodes["Object106_18_-_Default_0"].geometry}
                material={materials["18_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[224.33, 187.76, -39.63]}
            rotation={[-2.74, 0.43, 1.84]}
            scale={1.48}
          >
            <group position={[1.25, -1.29, -1.24]}>
              <mesh
                geometry={nodes["Box047_Material_#504_0"].geometry}
                material={materials.Material_504}
              />
            </group>
          </group>
          <group
            position={[222.65, 190.32, -34.49]}
            rotation={[-1.64, 0.63, 2.53]}
            scale={1.77}
          >
            <group position={[0.25, -1.14, 1.12]}>
              <mesh
                geometry={nodes["Plane016_Material_#504_0"].geometry}
                material={materials.Material_504}
              />
            </group>
          </group>
          <group
            position={[216.58, 188.43, -35.29]}
            rotation={[-1.08, 0.08, 2.75]}
            scale={1.77}
          >
            <mesh
              geometry={nodes["Plane017_Material_#508_0"].geometry}
              material={materials.Material_508}
            />
          </group>
          <group
            position={[223.96, 188.51, -31.06]}
            rotation={[1.84, 0.57, -2.15]}
            scale={[-1.77, 1.77, 1.77]}
          >
            <mesh
              geometry={nodes["Plane018_Material_#507_0"].geometry}
              material={materials.Material_507}
            />
          </group>
          <group
            position={[1.78, 463.79, -64.94]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.81}
          >
            <group position={[0, -148.49, -495.03]}>
              <mesh
                geometry={nodes["Object001_Material_#648_0"].geometry}
                material={materials.Material_648}
              />
            </group>
          </group>
          <group
            position={[1.78, 545.13, -159.02]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.66}
          >
            <mesh
              geometry={nodes["Object115_Material_#537_0"].geometry}
              material={materials.Material_537}
            />
          </group>
          <group
            position={[-296.79, 205.56, -65.81]}
            rotation={[-Math.PI / 2, 0, 0.87]}
          >
            <mesh
              geometry={nodes["Barrel007_Material_#496_0"].geometry}
              material={materials.Material_496}
            />
          </group>
          <group
            position={[-316.55, 281.61, -65.81]}
            rotation={[-Math.PI / 2, -0.1, 0.87]}
          >
            <mesh
              geometry={nodes["Barrel008_Material_#496_0"].geometry}
              material={materials.Material_496}
            />
          </group>
          <group
            position={[294.8, 206.94, -77.75]}
            rotation={[-Math.PI / 2, 0, 1.64]}
          >
            <mesh
              geometry={nodes["Barrel009_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[315.16, 284.61, -72.82]}
            rotation={[-1.73, 0.29, 1.84]}
          >
            <mesh
              geometry={nodes["Barrel010_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[1.78, 600.93, -456.55]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.39}
          >
            <group position={[-485.1, 82.96, -122.14]}>
              <mesh
                geometry={nodes["Object127_Material_#537_0"].geometry}
                material={materials.Material_537}
              />
            </group>
          </group>
          <group
            position={[1.78, 575.49, -456.94]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.59}
          >
            <group position={[-413.13, 0, 37.02]}>
              <mesh
                geometry={nodes["Box050_Material_#560_0"].geometry}
                material={materials.Material_560}
              />
            </group>
          </group>
          <group
            position={[269.14, 228.84, 301.92]}
            rotation={[-Math.PI / 2, 0, 1.63]}
          >
            <mesh
              geometry={nodes["Object128_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
            />
          </group>
          <group position={[1.78, 1.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["WoodenSupport_Material_#561_0"].geometry}
              material={materials.Material_561}
            />
          </group>
          <group
            position={[1.78, 448.14, -109.19]}
            rotation={[-2.88, 0, Math.PI / 2]}
            scale={[1.6, 1.85, 1.56]}
          >
            <mesh
              geometry={nodes["Object129_Material_#575_0"].geometry}
              material={materials.Material_575}
            />
          </group>
          <group
            position={[1.55, 167.22, 197.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.18, 1.18, 1.12]}
          >
            <mesh
              geometry={nodes["Object130_Material_#495_0"].geometry}
              material={materials.Material_495}
            />
          </group>
          <group
            position={[79.42, 318.3, -49.62]}
            rotation={[1.17, 0.65, 0.08]}
            scale={1.52}
          >
            <mesh
              geometry={nodes["Object133_09_-_Default_0"].geometry}
              material={materials["09_-_Default"]}
            />
          </group>
          <group
            position={[193.8, 256.28, 220.42]}
            rotation={[1.58, -0.04, 0.9]}
            scale={1.5}
          >
            <mesh
              geometry={nodes["Object134_09_-_Default_0"].geometry}
              material={materials["09_-_Default"]}
            />
          </group>
          <group
            position={[-255.53, 253.37, 144.05]}
            rotation={[-Math.PI / 2, 0, 1.77]}
            scale={[14.66, 14.66, 14.21]}
          >
            <group position={[-10.56, 5.37, 0.04]}>
              <mesh
                geometry={nodes["Object136_14_-_Default_0"].geometry}
                material={materials["14_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[-31.5, 249.96, 233.48]}
            rotation={[-Math.PI / 2, 0, 1.47]}
            scale={[9.5, 9.5, 9.21]}
          >
            <group position={[-6.42, 29.66, -0.51]}>
              <mesh
                geometry={nodes.Object139__TomeOpendefault_0.geometry}
                material={materials.TomeOpendefault}
              />
            </group>
          </group>
          <group
            position={[-263.48, 250.1, 182.68]}
            rotation={[-Math.PI / 2, 0, 0.26]}
            scale={0.94}
          >
            <group position={[-4.18, 0, -248.55]}>
              <mesh
                geometry={nodes["Box051_13_-_Default_0"].geometry}
                material={materials["13_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[-238.7, 246.94, 245.02]}
            rotation={[-Math.PI / 2, 0, 1.47]}
            scale={[14.2, 14.2, 15.15]}
          >
            <group position={[-3.06, 8.09, 0.91]}>
              <mesh
                geometry={nodes["Object140_02_-_Default_0"].geometry}
                material={materials["02_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[-31.5, 250.33, 233.48]}
            rotation={[-Math.PI / 2, 0, 1.47]}
            scale={[9.5, 9.5, 9.21]}
          >
            <group position={[-6.42, 29.66, -0.51]}>
              <mesh
                geometry={nodes.Object141__TomeOpendefault_0.geometry}
                material={materials.TomeOpendefault}
              />
            </group>
          </group>
          <group
            position={[-239.96, 263.92, 228.46]}
            rotation={[-Math.PI / 2, 0, -1.99]}
            scale={[1.68, 1.68, 1.12]}
          >
            <group position={[-9.81, 8.07, -39.21]}>
              <mesh
                geometry={nodes["Object142_15_-_Default_0"].geometry}
                material={materials["15_-_Default"]}
              />
            </group>
          </group>
          <group
            position={[-237.88, 230.88, 228.71]}
            rotation={[-1.54, 0.03, 0]}
            scale={0.32}
          >
            <mesh
              geometry={nodes["Sphere001_15_-_Default_0"].geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[204.37, 245.47, 182.72]}
            rotation={[-Math.PI / 2, 0, 1.47]}
            scale={[9.5, 9.5, 9.21]}
          >
            <group position={[-14.18, 53.83, 0.05]}>
              <mesh
                geometry={nodes["Object143_Material_#577_0"].geometry}
                material={materials.Material_577}
              />
            </group>
          </group>
          <group
            position={[-218.67, 224.98, 71.04]}
            rotation={[-1.61, 0, -0.39]}
            scale={1.26}
          >
            <mesh
              geometry={nodes["Cage006_Material_#439_0"].geometry}
              material={materials.Material_439}
            />
          </group>
          <group
            position={[234.42, 225.9, -50.83]}
            rotation={[-Math.PI / 2, 0, 1.2]}
            scale={1.25}
          >
            <mesh
              geometry={nodes["Cage007_Material_#439_0"].geometry}
              material={materials.Material_439}
            />
          </group>
          <group
            position={[0, 278.85, -68.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.02, 1, 1]}
          >
            <group position={[265.6, -420.18, -142.44]}>
              <mesh
                geometry={nodes["Walls_Material_#490_0"].geometry}
                material={materials.Material_490}
              />
            </group>
          </group>
          <group
            position={[266.1, 234.69, 163.67]}
            rotation={[0.1, -1.49, 0.02]}
            scale={[0.66, 0.66, 0.29]}
          >
            <mesh
              geometry={nodes["TomeO013_Material_#521_0"].geometry}
              material={materials.Material_521}
            />
          </group>
          <group
            position={[-214.82, 233.88, 183.24]}
            rotation={[-1.61, 0.05, 0]}
            scale={[0.97, 0.97, 0.43]}
          >
            <mesh
              geometry={nodes["TomeO014_Material_#628_0"].geometry}
              material={materials.Material_628}
            />
          </group>
          <group
            position={[187.31, 238.63, 246.48]}
            rotation={[-1.88, -0.89, -1.93]}
            scale={3.94}
          >
            <group position={[0.25, -1.14, 1.12]}>
              <mesh
                geometry={nodes["Plane022_Material_#465_0"].geometry}
                material={materials.Material_465}
              />
            </group>
          </group>
          <group
            position={[246.78, 241.55, 165.56]}
            rotation={[-1.5, -0.43, -2.97]}
            scale={[0.79, 0.79, 0.35]}
          >
            <mesh
              geometry={nodes["TomeOA002_Material_#630_0"].geometry}
              material={materials.Material_630}
            />
          </group>
          <group
            position={[269.14, 228.84, 301.92]}
            rotation={[-Math.PI / 2, 0, 1.63]}
          >
            <mesh
              geometry={nodes["Candles_Material_#631_0"].geometry}
              material={materials.Material_631}
            />
          </group>
          <group
            position={[-23.54, 174.9, -46.54]}
            rotation={[3.11, -0.54, 3.09]}
            scale={[0.96, 0.96, 0.42]}
          >
            <mesh
              geometry={nodes["TomeO015_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-23.12, 191.53, -46.98]}
            rotation={[2.95, -0.54, 3.07]}
            scale={[0.88, 0.88, 0.39]}
          >
            <mesh
              geometry={nodes["TomeO016_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-164.95, 238.23, -52.9]}
            rotation={[0.04, 0.11, -0.13]}
            scale={[0.62, 0.62, 0.27]}
          >
            <mesh
              geometry={nodes["TomeO017_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-161.95, 320.89, -32.14]}
            rotation={[-3.12, -0.04, -1.66]}
            scale={[0.58, 0.58, 0.25]}
          >
            <mesh
              geometry={nodes["TomeO018_Material_#638_0"].geometry}
              material={materials.Material_638}
            />
          </group>
          <group
            position={[-144.96, 319.34, -33.32]}
            rotation={[-3.11, -0.02, -1.19]}
            scale={[0.58, 0.58, 0.25]}
          >
            <mesh
              geometry={nodes["TomeO019_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-172.25, 318.7, -35.75]}
            rotation={[-3.12, 0.04, 1.6]}
            scale={[-0.47, 0.47, 0.21]}
          >
            <mesh
              geometry={nodes["TomeO020_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-192.99, 323.55, -31.52]}
            rotation={[3.13, -0.2, -1.76]}
            scale={[0.58, 0.58, 0.25]}
          >
            <mesh
              geometry={nodes["TomeO021_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[-21.87, 205.73, -47.32]}
            rotation={[2.83, -0.51, 3.07]}
            scale={[0.81, 0.81, 0.35]}
          >
            <mesh
              geometry={nodes["TomeO022_Material_#640_0"].geometry}
              material={materials.Material_640}
            />
          </group>
          <group
            position={[-160.38, 247.66, -52.9]}
            rotation={[0.03, 0.11, -0.08]}
            scale={[0.53, 0.53, 0.23]}
          >
            <mesh
              geometry={nodes["TomeO023_Material_#641_0"].geometry}
              material={materials.Material_641}
            />
          </group>
          <group
            position={[181.09, 321.36, -35.79]}
            rotation={[-3.12, -0.03, -1.5]}
            scale={[0.58, 0.58, 0.25]}
          >
            <mesh
              geometry={nodes["TomeO024_Material_#632_0"].geometry}
              material={materials.Material_632}
            />
          </group>
          <group
            position={[167.2, 321.71, -35.79]}
            rotation={[-3.12, -0.04, -1.7]}
            scale={[0.58, 0.58, 0.25]}
          >
            <mesh
              geometry={nodes["TomeO025_Material_#638_0"].geometry}
              material={materials.Material_638}
            />
          </group>
          <group
            position={[91.15, 211.06, -37.74]}
            rotation={[3.11, 0.04, 3.08]}
            scale={[0.62, 0.62, 0.27]}
          >
            <mesh
              geometry={nodes["TomeO026_Material_#639_0"].geometry}
              material={materials.Material_639}
            />
          </group>
          <group
            position={[-97.61, 209.11, -52.9]}
            rotation={[0.01, 0.48, -0.05]}
            scale={[0.43, 0.43, 0.19]}
          >
            <mesh
              geometry={nodes["TomeO027_Material_#643_0"].geometry}
              material={materials.Material_643}
            />
          </group>
          <group
            position={[-102.98, 215.39, -49.54]}
            rotation={[-0.04, 0.72, 0.02]}
            scale={[0.43, 0.43, 0.19]}
          >
            <mesh
              geometry={nodes["TomeO028_Material_#644_0"].geometry}
              material={materials.Material_644}
            />
          </group>
          <group
            position={[4.07, 709.13, -150.28]}
            rotation={[-Math.PI / 2, -0.09, 0]}
            scale={0.6}
          >
            <group position={[-486.56, 866.64, -434.72]}>
              <mesh
                geometry={nodes["Object144_Material_#537_0"].geometry}
                material={materials.Material_537}
              />
            </group>
          </group>
          <group
            position={[-182.8, 320.65, -32.14]}
            rotation={[-3.12, -0.04, -1.75]}
            scale={[0.49, 0.49, 0.22]}
          >
            <mesh
              geometry={nodes["TomeO029_Material_#638_0"].geometry}
              material={materials.Material_638}
            />
          </group>
          <group position={[0, 677.12, -61.67]} scale={1.72}>
            <group position={[-209.51, 119.36, -12.86]}>
              <mesh
                geometry={nodes["Plane024_Material_#646_0"].geometry}
                material={materials.Material_646}
              />
            </group>
          </group>
          <group
            position={[-78, 291.94, 120.62]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes["Plane025_Material_#647_0"].geometry}
              material={materials.Material_647}
            />
          </group>
          <group position={[0, 390.89, -278.31]}>
            <group position={[231.53, -10.54, 278.31]}>
              <mesh
                geometry={nodes["Line002_Material_#678_0"].geometry}
                material={materials.Material_678}
              />
            </group>
          </group>
          <group position={[0, 390.89, -278.31]}>
            <group position={[231.53, -10.54, 278.31]}>
              <mesh
                geometry={nodes["Object146_Material_#717_0"].geometry}
                material={materials.Material_717}
              />
            </group>
          </group>
          <group position={[0, 414.77, -109.37]}>
            <group position={[231.53, -34.42, 109.37]}>
              <mesh
                geometry={nodes["Object149_Material_#676_0"].geometry}
                material={materials.Material_676}
              />
            </group>
          </group>
          <group
            position={[-256.25, 207.66, -65.51]}
            rotation={[-Math.PI / 2, 0, 2.08]}
          >
            <mesh
              geometry={nodes["Barrel011_Material_#437_0"].geometry}
              material={materials.Material_437}
            />
          </group>
          <group
            position={[-256.83, 234.29, -66.57]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.71, 0.71, 0.61]}
          >
            <group position={[-1.47, 0, -59.53]}>
              <mesh
                geometry={nodes["Object150_Material_#495_0"].geometry}
                material={materials.Material_495}
              />
            </group>
          </group>
          <group
            position={[-254.15, 355.16, -61.26]}
            rotation={[-1.61, 0, 1.96]}
            scale={[15.93, 15.93, 9.94]}
          >
            <group position={[-9.77, 8.09, -40.5]}>
              <mesh
                geometry={nodes["Object151_18_-_Default_0"].geometry}
                material={materials["18_-_Default"]}
              />
            </group>
          </group>
          <group position={[0, 390.89, -278.31]}>
            <group position={[231.53, -10.54, 278.31]}>
              <mesh
                geometry={nodes["Object152_Material_#677_0"].geometry}
                material={materials.Material_677}
              />
            </group>
          </group>
          <group
            position={[0.22, 580.99, -476.26]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes["Plane026_Material_#715_0"].geometry}
              material={materials.Material_715}
            />
          </group>
          <group position={[0, 590.67, -474.93]} scale={[1.25, 1.25, 1]}>
            <mesh
              geometry={nodes["Object153_Material_#650_0"].geometry}
              material={materials.Material_650}
            />
          </group>
          <group
            position={[122.21, 270.67, -55.22]}
            rotation={[0, -0.07, 0]}
            scale={[1, 1, 1.22]}
          >
            <group position={[0, -14.07, -17.01]}>
              <mesh
                geometry={nodes["Object154_Material_#497_0"].geometry}
                material={materials.Material_497}
              />
            </group>
          </group>
          <group
            position={[-129.96, 270.67, -50.03]}
            rotation={[0, 0.06, 0]}
            scale={[0.96, 1, 1]}
          >
            <group position={[0, -14.07, -17.01]}>
              <mesh
                geometry={nodes["Object155_Material_#497_0"].geometry}
                material={materials.Material_497}
              />
            </group>
          </group>
          <group position={[0, 590.67, -474.93]} scale={[1.25, 1.25, 1]}>
            <mesh
              geometry={nodes["Object156_Material_#682_0"].geometry}
              material={materials.Material_682}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["Object157_Material_#680_0"].geometry}
              material={materials.Material_680}
            />
          </group>
          <group
            position={[1.38, 153.72, -83.85]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes["Plane027_Material_#716_0"].geometry}
              material={materials.Material_716}
            />
          </group>
          <group
            position={[0, 280.15, -586.51]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Object158_Material_#714_0"].geometry}
              material={materials.Material_714}
            />
          </group>
          <group
            position={[0, 278.85, -68.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.02, 1, 1]}
          >
            <group position={[265.6, -420.18, -142.44]}>
              <mesh
                geometry={nodes["Floor_Material_#491_0"].geometry}
                material={materials.Material_491}
              />
            </group>
          </group>
          <group
            position={[0, 278.85, -68.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.02, 1, 1]}
          >
            <group position={[265.6, -420.18, -142.44]}>
              <mesh
                geometry={nodes["TrimGeo_Material_#649_0"].geometry}
                material={materials.Material_649}
              />
            </group>
          </group>
          <group position={[0, 577.44, -474.78]}>
            <mesh
              geometry={nodes["Object159_Material_#681_0"].geometry}
              material={materials.Material_681}
            />
          </group>
          <group
            position={[0, 280.15, -586.51]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Object160_Material_#681_0"].geometry}
              material={materials.Material_681}
            />
          </group>
          <group
            position={[-31.5, 249.96, 233.48]}
            rotation={[-Math.PI / 2, 0, 1.47]}
            scale={[9.5, 9.5, 9.21]}
          >
            <group position={[-6.42, 29.66, -0.51]}>
              <mesh
                geometry={nodes["Object161_Material_#718_0"].geometry}
                material={materials.Material_718}
              />
            </group>
          </group>
          <group
            position={[-31.5, 249.96, 233.48]}
            rotation={[-Math.PI / 2, 0, 1.47]}
            scale={[9.5, 9.5, 9.21]}
          >
            <group position={[-6.42, 29.66, -0.51]}>
              <mesh
                geometry={nodes["Object162_Material_#719_0"].geometry}
                material={materials.Material_719}
              />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["HeroCauldron_LP_Material_#683_0"].geometry}
              material={materials.Material_683}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/undercity.gltf");
